name: GitHub Actions Demo
on:
    push:
        branches:
            - master
    schedule:
        - cron: "* * * * *"
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Running
              run: |
                  echo "Running!"
